### ISSUE TITLE
missing mix.lock prevents building from upstream

### ISSUE THREAD

**Issue by abreksa4** [CaliDog/certstream-server#12]
Currently, the repository doesn't contain `mix.lock`, and the Dockerfile explicitly adds it. That requires us to pull in the source by either forking the repo to edit the Dockerfile or support generating the file in CI/CD.

Thoughts on either excluding the `mix.lock` from being _explicitly_ added in the Dockerfile or committing the version you'd like to include?

**Comment by Fitblip** [comment]
@abreksa4 - sorry for the delay here. 

You're totally right! That's definitely my bad. I'll commit a mix.lock file!

**Comment by Fitblip** [comment]
Fixed with https://github.com/CaliDog/certstream-server/commit/3a39fceef991d895c6196d6338f529930fcaf239!

**Comment by abreksa4** [comment]
No problem, and thanks!
