### ISSUE TITLE
Add ability to configure a user agent

### ISSUE THREAD

**Issue by pgporada** [CaliDog/certstream-server#13]
Hi,

Would it be possible to add the ability to set a default user agent and the ability for a user to configure a custom user agent? This would help CT log operators know the software that researchers are using to scrape information.

**Comment by Fitblip** [comment]
Sounds possible! We use HTTPoison for all requests, so if you can find a way to get that to send headers properly, I'd be happy to review a PR!

**Comment by Fitblip** [comment]
@pgporada - With the release of 1.3.0 this should be implemented! By default now we'll send a user agent of `Certstream Server vX.X.X` (where X is the current version), and if you want to override it with your own user agent string you can just do something like this in `config.exs`:

```
config :certstream,
       user_agent: "This is my custom user agent!"
```

Thanks for the report and have a good weekend!

**Comment by pgporada** [comment]
Cool! Thank you very much!
