### ISSUE TITLE
Broken Dockerfile

### ISSUE THREAD

**Issue by alsyia** [CaliDog/certstream-server#31]
Hello,

Thanks for this amazing tool ! Just wanted to let you know that the Dockerfile does not build on `master`.
I think there are two issues:
* `html` directory has been renamed to `frontend` in 38bf4fe72d1144cd03ce9c0dc663d914350831ce so the Dockerfile should be updated accordingly (line 19):
```
- COPY html/dist/ /opt/app/html/dist/
+ COPY frontend/dist/ /opt/app/frontend/dist/
```
* Dependency `instruments` is sourced from Git but the base image doesn't have Git, so something like `RUN apk add git` is needed in the Dockerfile (although my understanding is that this one is temporary?)

It works on my workstation with this two fixes.

Please let me know if I can help (by doing the PR maybe?)! 

Thank you :smile:

**Comment by Fitblip** [comment]
Doh! Sorry for the breakage. If you want to submit a PR I’ll happily review
otherwise I’ll have to get to it once things settle down work-wise (likely
this weekend).

Thanks for the heads up!

**Comment by alsyia** [comment]
No worries! I did the PR, please tell me if there is anything wrong, and thank you for your time! :)
