### ISSUE TITLE
Way of retrieving certificates from CT logs : possibility to miss certificates or not ?

### ISSUE THREAD

**Issue by cbrocas** [CaliDog/certstream-server#4]
Hello,

First, we ( @AssuranceMaladieSec ) would like to thank you for open sourcing Certstream client, server AND maintaining a Certstream server instance. We have been able to build on top of them https://github.com/AssuranceMaladieSec/CertStreamMonitor , a tool for using CT for BlueTeams :)

We are currently testing your server code and we note that kind of messages : 
14:40:51.892 [error] Error fetching url https://ct.ws.symantec.com/ct/v1/get-sth: closed! Sleeping for a bit and trying again...

Our question : when the server will successfully reconnect to this particular log, will the code restart at the exact location in the log and not lose any certificate due to the lost of connection or will there be some certificates that will possibly be skipped ?

Thanks in advance 
Christophe

**Comment by Fitblip** [comment]
Hey @cbrocas, sorry for the late response!

In this scenario it should (in theory) rebroadcast those certificates as it uses the merkle tree height as an offset to get to for what certificates to retrieve and rebroadcast. To be clear though, I haven't tested Certstream in really any failure conditions, so it'd definitely worth confirming/investigating. Always happy to add logging to aid in testing if you feel like making a PR!

Cheers,
Ryan

**Comment by Fitblip** [comment]
Hi there, I think this is closed/stale so I'm closing it. Hope you've been well!
