### ISSUE TITLE
Fetch just all_domains

### ISSUE THREAD

**Issue by mkb2091** [CaliDog/certstream-server#42]
Is there a way to fetch just message['data']['leaf_cert']['all_domains'] data? That would reduce unnecessary data transfer for clients that don't need the rest of the data

**Comment by Fitblip** [comment]
Not yet, but in #38 I added in a slimmer standard default stream that doesn't give the same (large) amount of data. It should be similar to add an "extra light" stream since I agree a lot of people use this just to look at that field.

**Comment by Fitblip** [comment]
This is fixed in #55, let me know if you have something else in mind!
