### ISSUE TITLE
Broken link to "supervisor configurations" in README

### ISSUE THREAD

**Issue by AKarbas** [CaliDog/certstream-server#45]
Hi!

The Link to "supervisor configurations" is broken.
It's on line 53 of the readme: [Link](https://github.com/CaliDog/certstream-server/blob/64e4a8689538216afbb654d98dd2c2985a3ac3ad/README.md#L53).

Cheers.

**Comment by Synse** [comment]
`lib/supervisor.ex` was removed in 354138e.

The readme should probably be updated to point at [lib/application.ex](https://github.com/CaliDog/certstream-server/blob/master/lib/application.ex).

**Comment by AKarbas** [comment]
I was about to create a PR changing the link, but I really don't find the sentence "is essentially entirely outlined in the supervisor configuration." in the readme true.

Maybe it's because I don't know Elixir, but that link does not help me understand the internals!
The drawn schema is pretty simple to understand tho.

Why not remove the first paragraph?

**Comment by AKarbas** [comment]
As is obvious, created a PR.
The end result makes the most sense to me.
