### ISSUE TITLE
Move data.chain to full-stream

### ISSUE THREAD

**Issue by Synse** [CaliDog/certstream-server#47]
If https://github.com/CaliDog/EasySSL/pull/11 is merged and version bumped here it would add `issuer` to the `leaf_cert` data.

I think adding the issuer and moving `chain` to `/full-stream` would reduce the data transfer for most use cases.

For anyone that needs the full issuing chain, everything would still be available (albeit slightly larger with the der encoded certificate and new issuer field) in the full stream.

**Comment by Fitblip** [comment]
Yeah agreed, I think most people are using the stream to just read the "all dns names" array, and this would probably be good to do. Not sure when I'll have time to get to it, but I might find a random day to do it!

**Comment by Synse** [comment]
The PR mentioned above was merged and c672a9b bumped EasySSL from 1.1.2 to 1.3.0 so `issuer` (and some other fields) are now included for `leaf_cert` (and certs in `chain`) so this should be viable now.

I'll also take a look if I get some free time.

**Comment by Fitblip** [comment]
Hey there @Synse, thanks for the suggestion. This is implemented in #56, and will be live on certstream.calidog.io shortly! 

Let me know if you run into any issues :)

**Comment by Synse** [comment]
Just following up to say this is working great, thanks for implementing!
