### ISSUE TITLE
certstream server connection error (SSL: Unknown protocol)

### ISSUE THREAD

**Issue by june5079** [CaliDog/certstream-server#63]
Hi,

I set certstream server with exilir on cent OS 7 and seems to work fine.
(Web page works)

At another server, I set certstream-python and chaned wss server from calidog to my local server like below

certstream.listen_for_events(callback, url='wss://10.10.10.10:8080/')  --> I changed port number

when I run the python code, error occur like this.

``` certificate_update: 0cert [00:00, ?cert/s]Error connecting to CertStream - [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1123) - Sleeping for a few seconds and trying again... ```

Do you have any idea to solve this?

**Comment by Fitblip** [comment]
Yeah this is likely not listening on a secure socket. 

Try this:

```
certstream.listen_for_events(callback, url='ws://10.10.10.10:8080/')
```

Note `wss` -> `ws`
